[package]
name = "yaml2json"
version = "0.1.0"
authors = ["Przemysław K. Rekucki <przemyslaw.rekucki@golem.network>"]

[dependencies]
serde = "1.0"
serde_yaml = "0.8"
serde_json="1.0"
structopt = { version = "0.2", default-features = false }
failure="0.1"
